# Generated by Django 3.2.12 on 2022-04-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='student_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
