# Generated by Django 3.2.12 on 2022-04-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20220412_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='join_date',
            field=models.DateField(),
        ),
    ]
